### ISSUE TITLE
Implementing IPFS to save DAO logo

### ISSUE THREAD

**Issue by crisog** [fbfly/website#12]
We are having a custom logo for each DAO, so we may want to save that on IPFS.

This would also need some kind of mapping from our side: DAO (address) <-> IPFS path

**Comment by dan13ram** [comment]
What do you think about using this https://docs.fleek.co/storage/fleek-storage-js/

**Comment by crisog** [comment]
> What do you think about using this https://docs.fleek.co/storage/fleek-storage-js/

That would also work pretty well I'd say.
