### ISSUE TITLE
Linking entities: FB Group Id <-> DAO (address) <-> FB User Id

### ISSUE THREAD

**Issue by crisog** [fbfly/website#13]
We are going to stick to the 1 DAO per FB Group model. 

- We need to have a way to determine whether '0x....' address belongs to which FB Group.
- We also need to check the members of the DAO which is easily accessible with Connect, but rather than just knowing the addresses, having a link between a certain person's address & their FB Id.

This can be either done by using a DB on IPFS: https://github.com/orbitdb/orbit-db or by having a contract with key-value pairs with this information.

FB Group Id <-> DAO (address) <-> FB User Id

**Comment by dan13ram** [comment]
i see these 4 different identites that need linking :
user's 0x address
dao's 0x address
fb groud id
fb user id

what kind of linking we are looking for ?
what kind of querying will be need to do ?
also where will we store the dao metadata information that we are gathering?
i.e.
dao title
dao description/about
dao logo ipfs hash

answering these questions will give us more clarity on where to store this data

**Comment by dan13ram** [comment]
regarding members fb ids being linked to eth addresses:
we can only possibly do this if all of these members login to our UI atleast once.

**Comment by crisog** [comment]
> i see these 4 different identites that need linking :
> user's 0x address
> dao's 0x address
> fb groud id
> fb user id
> 
> what kind of linking we are looking for ?
> what kind of querying will be need to do ?
> also where will we store the dao metadata information that we are gathering?
> i.e.
> dao title
> dao description/about
> dao logo ipfs hash
> 
> answering these questions will give us more clarity on where to store this data

0x address and FB user Id are linked out of the box with Tor.us

I think that some of the queries we may need are:

- Check if a FB Group has a DAO linked to it, to avoid more than 1 DAO for a certain FB group.
- Check what are the DAO addresses that a certain FB user (0x address) has access to.

For the DAO metadata, we should have them also linked to the DAO address so we can retrieve it later as we want. Not really sure where we can store this.

**Comment by crisog** [comment]
Maybe we can store DAO metadata with this: https://github.com/orbitdb/orbit-db-docstore

**Comment by dan13ram** [comment]
Is it possible to get the FB userID given ETH addess (0x  ... ) ?
The opposite flow works : https://docs.tor.us/torus-wallet/api-reference/address-resolver
Because the aragon connect with return members as eth addresses and we will need to display fb userIds given the 0x address.
If they dont provide it then we will need a database for the same.

**Comment by dan13ram** [comment]
what about a smart contract on the xDAI network? The gas fees will be paid in xDai i believe. 
https://www.xdaichain.com/for-developers/smart-contract-deployment

**Comment by dan13ram** [comment]
> Maybe we can store DAO metadata with this: https://github.com/orbitdb/orbit-db-docstore

I wonder if it would be much simpler to create a json string with the metadata and store it directly on IPFS.
And we store the metadata hash on our smart contract.

**Comment by crisog** [comment]
We are getting some progress on this issue on PR #28
