### ISSUE TITLE
List of DAOs (Frontend)

### ISSUE THREAD

**Issue by crisog** [fbfly/website#22]
This is where the users can quickly check all the DAOs they have voting power.

![image](https://user-images.githubusercontent.com/40803711/87370938-4000b600-c552-11ea-9ef0-11e905b714b0.png)

Figma: https://www.figma.com/file/2Y6R6uilTpxoz6UMdeGyWO/Untitled?node-id=0%3A1

**Comment by befitsandpiper** [comment]
So, This is going to be a row for every DAO, right? And then you click on the row and it goes to info page for that DAO?

**Comment by crisog** [comment]
> So, This is going to be a row for every DAO, right? And then you click on the row and it goes to info page for that DAO?

Exactly. Every DAO linked to that specific user will show up there and if any of them is clicked it will redirect them

**Comment by befitsandpiper** [comment]
Plan on starting on this tomorrow, and hopefully finishing, but we'll see. Is this due at any particular time other than by the deadline next week? If I don't get it done tomorrow my goal is to be finished by Monday.

**Comment by crisog** [comment]
> Plan on starting on this tomorrow, and hopefully finishing, but we'll see. Is this due at any particular time other than by the deadline next week? If I don't get it done tomorrow my goal is to be finished by Monday.

I think that if you can get it done for Monday it's okay :). Make a separate branch on this repo so we can all be aware.
